-- ==========================================
-- SCHEMA SUPABASE - SORTE DO DIA
-- Cole e execute no SQL Editor do Supabase
-- ==========================================

-- 1. Tabela de Casas de Aposta
CREATE TABLE IF NOT EXISTS casas_aposta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  url TEXT NOT NULL,
  ativa BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insere as casas padrão
INSERT INTO casas_aposta (nome, url, ativa) VALUES 
  ('Betano', 'https://www.betano.com.br', true),
  ('Bet365', 'https://www.bet365.com', true),
  ('Sportingbet', 'https://www.sportingbet.com', false);


-- 2. Tabela de Tipos de Aposta
CREATE TABLE IF NOT EXISTS tipos_aposta (
  chave TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  mercado TEXT NOT NULL,
  linha NUMERIC,
  ativa BOOLEAN DEFAULT true
);

-- Insere os tipos padrão
INSERT INTO tipos_aposta (chave, label, mercado, linha, ativa) VALUES
  ('resultado_final', 'Resultado Final (1X2)', 'h2h', NULL, true),
  ('ambas_marcam', 'Ambas Marcam (BTTS)', 'btts', NULL, true),
  ('dupla_chance', 'Dupla Chance (1X, X2, 12)', 'double_chance', NULL, true),
  ('over_under', 'Over/Under Gols (2.5)', 'totals', 2.5, true),
  ('handicap_asiatico', 'Handicap Asiático', 'asian_handicap', NULL, false),
  ('escanteios', 'Total de Escanteios', 'corners', NULL, false),
  ('cartoes', 'Total de Cartões', 'cards', NULL, false);


-- 3. Tabela de Configurações (Chave/Valor)
CREATE TABLE IF NOT EXISTS configuracoes (
  chave TEXT PRIMARY KEY,
  valor JSONB NOT NULL
);

-- Insere as configurações padrão
INSERT INTO configuracoes (chave, valor) VALUES 
  ('odds_api', '{"chave": "", "esportes": ["soccer_brazil_campeonato", "soccer_epl", "soccer_uefa_champs_league"], "regioes": ["eu", "uk"], "max_jogos_por_video": 3}'::jsonb),
  ('video', '{"largura": 1080, "altura": 1920, "fps": 30, "duracao_total": 40, "canal_nome": "Sorte do Dia", "canal_usuario": "@sortedodia01"}'::jsonb),
  ('agendamento', '{"ativo": false, "horarios": ["10:00", "15:00"]}'::jsonb);


-- 4. Histórico de Pipelines e Relatórios
CREATE TABLE IF NOT EXISTS historico_pipeline (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  status TEXT NOT NULL,
  jogos JSONB,
  video_url TEXT,
  logs JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS (Segurança).
-- Leitura é pública (dashboard e bot precisam ler). Escrita em casas_aposta,
-- tipos_aposta e configuracoes exige a service_role key (usada só no backend
-- do painel admin, atrás de senha) — a chave pública (anon/publishable) não
-- consegue mais escrever nessas tabelas.
ALTER TABLE casas_aposta ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipos_aposta ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE historico_pipeline ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leitura publica casas" ON casas_aposta FOR SELECT USING (true);
CREATE POLICY "Leitura publica tipos" ON tipos_aposta FOR SELECT USING (true);
CREATE POLICY "Leitura publica config" ON configuracoes FOR SELECT USING (true);

-- historico_pipeline: o bot Python (chave anon) grava os relatórios, então
-- leitura e escrita continuam abertas aqui.
CREATE POLICY "Acesso total historico" ON historico_pipeline FOR ALL USING (true);
